---
title: "ETC5512 Assignment 4: An Analysis of US Air Traffic"
subtitle: "Name of your airport"
author: "Firstname Lastname"
date: "June 19,  2020"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache=TRUE, 
                      messages=FALSE, 
                      warning=FALSE)
library(tidyverse)
library(DBI)
library(ggmap)
library(ggthemes)
# for exercise 2
library(lutz)
library(lubridate)
library(kableExtra)
library(janitor)
library(viridis)
```


## `r emo::ji("airplane")` Exercise 1

### a. 
```{r read flight data}
d <- read_csv(here::here("raw_data","On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2020_2.csv"))
```

```{r choose one carrier}
ca <- d %>%
  filter(Reporting_Airline == "UA")
save(ca, file = here::here("data","airlines.rda"))
```

```{r choose one airport}
airport <- d %>%
  filter(Origin == "ATL" | Dest == "ATL")
save(airport, file = here::here("data","airport_ATL.rda"))
```


Paragraph...

### b. 
```{r read airport data}
d1 <- read_csv(here::here("raw_data","516691980_T_MASTER_CORD.csv"))
```

```{r join d1 into airport}
airport_location <- d1 %>%
  filter(AIRPORT_IS_CLOSED == 0 & # select the airports are still on businesses at the time
           AIRPORT_IS_LATEST == 1 &
           AIRPORT_COUNTRY_CODE_ISO == "US") %>% 
  select(AIRPORT, DISPLAY_AIRPORT_NAME, LONGITUDE, LATITUDE)

flight <- airport %>%
  left_join(airport_location, by = c("Origin" = "AIRPORT")) %>%
  rename("Origin_lon" = "LONGITUDE","Origin_lat" = "LATITUDE") %>% # rename origin airport longitude and latitude
  left_join(airport_location, by = c("Dest" = "AIRPORT")) %>%
  rename("Dest_lon" = "LONGITUDE","Dest_lat" = "LATITUDE") # rename dest airport longitude and latitude

save(flight,file = here::here("data","flights.rda"))
```



### c. 
```{r generate a map of US}
usa_bbox <- c(-130, # min long
              20, # min lat
              -60, # max long
              55) # max lat

usa_map <- get_map(location = usa_bbox, source = "osm")
```


```{r flight path}
ggmap(usa_map) + geom_segment(data=flight, 
                     aes(x=Origin_lon, 
                         xend=Dest_lon,
                         y=Origin_lat,
                         yend=Dest_lat), 
                     colour="#9651A0", alpha=0.01) +
  geom_point(data=flight, aes(x=Origin_lon, Origin_lat),
             colour="#746FB2", alpha=0.1, size=1) +
  theme_map()
```



## `r emo::ji("airplane")` Exercise 2

### a. 
```{r standardise timezone}
flights_NYtime <- flight %>%
  filter(!is.na(Origin_lon)) %>%
  filter(!is.na(Dest_lon)) %>%
  filter(!is.na(DepTime)) %>%
  mutate(origin_tz = tz_lookup_coords(Origin_lat,
                                      Origin_lon, 
                                      warn = FALSE),
         dest_tz = tz_lookup_coords(Dest_lat,
                                    Dest_lon,
                                    warn = FALSE)) %>%
  mutate(Dep_DateTime = paste0(FlightDate, 
                           " ",
                           substr(DepTime, 1, 2),":", 
                           substr(DepTime, 3, 4), ":00")) %>%
  mutate(Origin_DateTime_NY = force_tzs(ymd_hms(Dep_DateTime),
      tzones = origin_tz, tzone_out = "America/New_York")) %>% # Normalise Dep DateTime
  mutate(Arr_DateTime = paste0(FlightDate,
                               " ",
                               substr(ArrTime, 1, 2),":", 
                               substr(ArrTime, 3, 4), ":00")) %>%
  mutate(Dest_DateTime_NY = force_tzs(ymd_hms(Arr_DateTime),
      tzones = dest_tz, tzone_out = "America/New_York"))

flights_NYtime %>%
  select(Origin_DateTime_NY, Dest_DateTime_NY, Tail_Number, Origin, Dest) %>%
  head()%>%
  kable(booktabs = TRUE, caption = "Flights-after normalise as NY Time")%>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```



### b. 
```{r list of plane}
# the list of planes that has flown in and out of the selected airport
flights_NYtime %>%
  group_by(Tail_Number, DayofMonth) %>%
  tally() %>%
  filter(n == 2) %>%
  select(Tail_Number, DayofMonth)
```

```{r choose one plane from the list above}
# Select a plane whose tail number was N7823A
day1 <- flights_NYtime %>%
  filter(Tail_Number == "N7823A", DayofMonth == 24)

ggmap(usa_map) +
  geom_segment(data=day1, 
                     aes(x=Origin_lon, 
                         xend=Dest_lon,
                         y=Origin_lat,
                         yend=Dest_lat), 
                     colour="Red", size = 1) +
  geom_point(data=day1, aes(x=Origin_lon, y = Origin_lat),
             colour="#746FB2", size=2) +
  geom_point(data=day1, aes(x=Dest_lon, y = Dest_lat),
             colour="#746FB2", size=2)
  theme_map()

```



### c. 
```{r animated fath way}
p1 <- day1 %>%
  mutate(AirTime_inter = AirTime/15) %>%
  mutate(Arr_DateTime = paste0(FlightDate, 
                           " ",
                           substr(ArrTime, 1, 2),":", 
                           substr(ArrTime, 3, 4), ":00"))%>%
  select(Origin_lon, Origin_lat, Dest_lon, Dest_lat, Dep_DateTime, Arr_DateTime, AirTime_inter)
```

```{r calculate the intervals}
p2 <-p1 %>%
  mutate(lon_inter = Dest_lon - Origin_lon,
         lat_inter = Dest_lat - Origin_lat) %>%
  mutate(lon_incre = lon_inter/AirTime_inter,
         lat_incre = lat_inter/AirTime_inter) %>%
  mutate(Dep_DateTime = ymd_hms(Dep_DateTime)) %>%
  arrange(Dep_DateTime)

p2
```

```{r}
step <- hms("00:15:00") # The time interval is 15 mins

p3 <- p2 %>%
  select(Origin_lon, Origin_lat, Dep_DateTime) %>%
  mutate(Dep_DateTime = ymd_hms(Dep_DateTime))
```

```{r generate sequences}
lon_1 <- as.tibble(seq(p2$Origin_lon[1], p2$Dest_lon[1], by = p2$lon_incre[1]))
lat_1 <- as.tibble(seq(p2$Origin_lat[1], p2$Dest_lat[1], by = p2$lat_incre[1]))
tibble1 <-bind_cols(lon_1,lat_1) %>% clean_names() %>%
  rename(Origin_lon = value_1, Origin_lat = value_2)


lon_2 <- as.tibble(seq(p2$Origin_lon[2], p2$Dest_lon[2], by = p2$lon_incre[2]))
lat_2 <- as.tibble(seq(p2$Origin_lat[2], p2$Dest_lat[2], by = p2$lat_incre[2]))
tibble2 <-bind_cols(lon_2,lat_2) %>% clean_names() %>%
  rename(Origin_lon = value_1, Origin_lat = value_2)

path <- bind_rows(p3[1,][1:2], tibble1, tibble2) #The movement of airplane

path$id <- seq.int(nrow(path))  
```

```{r one plane one path}
ggmap(usa_map)+
  geom_point(data=day1, 
             aes(x=Origin_lon, 
                 y=Origin_lat), 
             colour="Red", size = 1) +
  geom_point(data = path, aes(x = Origin_lon, y = Origin_lat, color = id)) +
          scale_color_viridis_c() +
  geom_point(data=day1, aes(x=Origin_lon, y = Origin_lat),
             colour="#746FB2", size=2) +
  geom_point(data=day1, aes(x=Dest_lon, y = Dest_lat),
             colour="#746FB2", size=2)+
  theme_map()
```







### d. 
```{r one plane, animation.hook='gifski', out.width="100%", fig.width=4, fig.height=2}
for (i in 1:nrow(path)){
  print(ggmap(usa_map)+
          geom_point(data=day1, aes(x=Origin_lon, y = Origin_lat),
             colour="Red", size=2) +
          geom_point(data=day1, aes(x=Dest_lon, y = Dest_lat),
             colour="Red", size=2) +
          geom_point(data = path, aes(x = path[[1]][i], y = path[[2]][i]),color = 'White') +
  theme_map())
}
```



### e. 

```{r}
flights_NYtime %>%
  filter(DayofMonth == 24, Reporting_Airline)
```





Here is one way to make an animation.

```{r, animation.hook='gifski', out.width="100%", fig.width=4, fig.height=2}
d <- tibble(koala=1:10, kangaroo=1:10)
for (i in 1:10){
  print(ggplot(data=d, aes(x=koala, y=kangaroo)) +
    geom_point(alpha=0.1) +
    geom_point(data=d[i,], colour="red"))
}
```

## `r emo::ji("airplane")` Exercise 3
```{r load nycflights13 package}
library(nycflights13)
names(nycflights13::flights)
```

```{r new data flights}
new_d <-read_csv(here::here("raw_data","On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2020_2.csv")) %>%
  select(Year, Month, DayofMonth, DepTime, CRSDepTime, DepDelay, ArrTime, CRSArrTime, ArrDelay, Reporting_Airline, Flight_Number_Reporting_Airline, Tail_Number, Origin, Dest, AirTime, Distance) %>%
  rename(Day = DayofMonth, sched_dep_time = CRSDepTime, sched_arr_time = CRSArrTime, Carrier = Reporting_Airline, Flight = Flight_Number_Reporting_Airline) %>%
  mutate(hour = substr(sched_dep_time,1,2), 
         minute = substr(sched_dep_time, 3, 4)) %>%
  mutate(time_hour = paste0(Year, "-", Month, "-", Day, 
                            " ",
                            hour, ":", minute)) %>%
  mutate(time_hour = as_datetime(time_hour, format = "%Y-%m-%d %H:%M")) %>%
  mutate(Year = as.integer(Year),
         Month = as.integer(Month),
         Day = as.integer(Day),
         DepTime = as.integer(DepTime),
         sched_dep_time = as.integer(sched_dep_time),
         ArrTime = as.integer(ArrTime),
         sched_arr_time = as.integer(sched_arr_time),
         Flight = as.integer(Flight),
         hour = as.double(hour),
         minute = as.double(minute)) %>%
  filter(Origin == "ATL" | Dest == "ATL")

save(new_d, file = here::here("data","ATL_feb_allcarriers.rda"))
```

```{r new data airlines}
# Download raw data
url_airlines <- ("https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat")
download.file(url_airlines, destfile = here::here("raw_data","airlines.csv"))

# Read data and add col names
new_airlines <- read_csv(here::here("raw_data","airlines.csv"), col_names = c("Airline ID", "Name", "Alias", "IATA", "ICAO", "Callsign", "Country", "Active")) %>%
  clean_names() %>% 
  filter(country == "United States", active =="Y")
  
new_airlines <- new_airlines %>%
  select(iata, name) %>%
  rename(carrier = iata)

save(new_airlines, file = here::here("data","my_airlines.rda"))
```

```{r new data airport}
# Download raw data
url_airport <- ("https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat") 
download.file(url_airport, destfile = here::here("raw_data","airports.csv"))

# Read data and add col names
new_airport <- read_csv(here::here("raw_data","airports.csv"), col_names = c("Airport ID", "Name", "City", "Country", "IATA", "ICAO", "Latitude", "Longitude", "Altitude", "Timezone", "DST", "Tz database time zone", "Type", "Source")) %>% 
  clean_names() %>%
  filter(country == "United States")

new_airport <- new_airport %>%
  select(iata, name, latitude, longitude, altitude, timezone, dst, tz_database_time_zone) %>%
  rename(faa = iata, lat = latitude, lon = longitude, alt = altitude, tz = timezone, tzone = tz_database_time_zone)

save(new_airport, file = here::here("data","airports.rda"))
```

```{r new data planes}
raw_planes <- read_csv(here::here("raw_data/ReleasableAircraft/MASTER.TXT")) %>% clean_names()
raw_engine <- read_csv(here::here("raw_data/ReleasableAircraft/ENGINE.TXT")) %>% clean_names()
raw_acf <- read_csv(here::here("raw_data/ReleasableAircraft/ACFTREF.TXT")) %>% clean_names()
```

```{r ducumentation}
# Find out the Descriptions for type engine and type aircraft
# Create table for Type Engine
type_engine <- tibble(type = c(0:11), engine_desc = c("None","Reciprocating", "Turbo-prop", "Turbo-shaft","Turbo-jet","Turbo-fan","Ramjet","2 Cycle","4 Cycle","Unknown","Electric","Rotary"))

# Create table for Type Aircraft
type_aircraft <- tibble(type = c(1:9,"H","O"), aircraft_desc = c("Glider","Balloon",
"Blimp/Dirigible",
"Fixed wing single engine",
"Fixed wing multi engine",
"Rotorcraft",
"Weight-shift-control",
"Powered Parachute",
"Gyroplane",
"Hybrid Lift",
"Other"))
```

```{r join tables into one}
# Join plane, engine, acf, type engine and type aircraft tables
raw_planes %>%
  left_join(raw_engine, by = c("eng_mfr_mdl" = "code")) %>%
  left_join(type_engine, by = "type") %>%
  left_join(raw_acf, by = c("mfr_mdl_code" = "code")) %>%
  mutate(type_acft = as.character(type_acft)) %>%
  left_join(type_aircraft, by = c("type_acft" = "type")) %>%
  clean_names() %>%
  select(n_number, # tailenum
         year_mfr,# year
         aircraft_desc, # type
         mfr_y, # manufacturer
         model_y, # model
         type, #engines in numeric
         no_seats, #seats
         speed, #speed
         engine_desc) %>% #engine in char
  # Rename col names
  rename(tailnum = n_number,
         year = year_mfr,
         type = aircraft_desc,
         manufacturer = mfr_y,
         model = model_y,
         engines = type,
         seats = no_seats,
         engine = engine_desc)
```



## `r emo::ji("airplane")` Exercise 4

## References

Cite  the main sources for your work, including R packages used.